name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Илова кардани линки Hugging Face ҳамчун репозиторияи алоҳида бо номи 'hf'
          git remote add hf https://x:$HF_TOKEN@huggingface.co/spaces/Mahmadmurodov/raonson
          
          # Маҷбуран партофтани бранчи main ба Hugging Face
          git push --force hf main
