name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        uses: huggingface/github-action@v3
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: Mahmadmurodov/raonson
          repo_type: space
