name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Боркунии мустақим тавассути воситаи расмии Hugging Face
          huggingface-cli upload Mahmadmurodov/raonson . . --repo-type=space --token=$HF_TOKEN
